version: '3.4'

services:
  app:
    
    build: ./app
    Links:
      - db
    ports:
      - 80:3000
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro